language: python
python:
  - "3.3"
# command to run tests
script: nosetests

notifications:
  irc:
    channels:
      - "chat.freenode.net#openpassword"
    on_success: always
    on_failure: always
